<?php

namespace App\Services;

class DefaultRules
{
    public static function getRules(): array
    {
        return [
            // ==================
            // General Attributes
            // ==================
            [
                'code' => 'TITLE_EXISTS',
                'name' => 'Title Tag Exists',
                'category' => 'General',
                'rule_type' => 'exist',
                'config' => ['selector' => 'title'],
                'severity' => 'error',
                'issue_message' => 'Tag <title> tidak ditemukan di dalam <head>.',
                'reason_template' => 'Setiap halaman HTML wajib memiliki tag <title>.',
                'recommendation' => 'Tambahkan tag <title>Judul Halaman</title> di bagian <head>.',
            ],
            [
                'code' => 'TITLE_LENGTH',
                'name' => 'Title Tag Length is Optimal',
                'category' => 'General',
                'rule_type' => 'length',
                'config' => [
                    'selector' => 'title',
                    'min' => 30,
                    'max' => 60,
                ],
                'severity' => 'warning',
                'issue_message' => 'Panjang karakter <title> tidak optimal (seharusnya antara 30-60 karakter).',
                'reason_template' => 'Title yang terlalu pendek kurang informatif, dan jika terlalu panjang akan terpotong di hasil pencarian.',
                'recommendation' => 'Sesuaikan judul agar panjangnya 30 hingga 60 karakter.',
            ],
            [
                'code' => 'TITLE_COUNT',
                'name' => 'Only One Title Tag',
                'category' => 'General',
                'rule_type' => 'count',
                'config' => [
                    'selector' => 'title',
                    'operator' => '=',
                    'expected' => 1,
                ],
                'severity' => 'error',
                'issue_message' => 'Ditemukan lebih dari satu tag <title>.',
                'reason_template' => 'Mesin pencari mungkin bingung jika terdapat beberapa tag <title> dalam satu halaman.',
                'recommendation' => 'Pastikan hanya ada tepat satu tag <title> di dalam dokumen.',
            ],
            [
                'code' => 'META_DESC_EXISTS',
                'name' => 'Meta Description Exists',
                'category' => 'General',
                'rule_type' => 'exist',
                'config' => ['selector' => 'meta[name="description"]'],
                'severity' => 'error',
                'issue_message' => 'Tag meta description tidak ditemukan.',
                'reason_template' => 'Meta description penting untuk memberikan ringkasan halaman pada hasil pencarian (CTR).',
                'recommendation' => 'Tambahkan <meta name="description" content="Deskripsi Anda"> di bagian <head>.',
            ],
            [
                'code' => 'META_DESC_LENGTH',
                'name' => 'Meta Description Length is Optimal',
                'category' => 'General',
                'rule_type' => 'attribute',
                'config' => [
                    'selector' => 'meta[name="description"]',
                    'attribute' => 'content',
                    'condition' => 'length_between',
                    'min' => 120,
                    'max' => 160,
                ],
                'severity' => 'warning',
                'issue_message' => 'Panjang meta description tidak optimal (seharusnya 120-160 karakter).',
                'reason_template' => 'Deskripsi yang terlalu panjang akan terpotong (truncated) oleh Google.',
                'recommendation' => 'Tulis ulang deskripsi agar padat, menarik, dan berada di kisaran 120-160 karakter.',
            ],
            [
                'code' => 'META_VIEWPORT',
                'name' => 'Viewport Meta Tag Exists',
                'category' => 'Technical',
                'rule_type' => 'exist',
                'config' => ['selector' => 'meta[name="viewport"]'],
                'severity' => 'error',
                'issue_message' => 'Tag meta viewport tidak ditemukan.',
                'reason_template' => 'Tanpa viewport, website tidak akan responsif di perangkat mobile (mobile-friendly).',
                'recommendation' => 'Tambahkan <meta name="viewport" content="width=device-width, initial-scale=1">.',
            ],
            [
                'code' => 'CANONICAL_EXISTS',
                'name' => 'Canonical Tag Exists',
                'category' => 'Metadata',
                'rule_type' => 'exist',
                'config' => ['selector' => 'link[rel="canonical"]'],
                'severity' => 'warning',
                'issue_message' => 'Tag canonical tidak ditemukan.',
                'reason_template' => 'Canonical tag mencegah masalah duplikasi konten (duplicate content) dengan menunjuk ke URL versi utama.',
                'recommendation' => 'Tambahkan <link rel="canonical" href="URL_UTAMA">.',
            ],
            [
                'code' => 'H1_EXISTS',
                'name' => 'H1 Tag Exists',
                'category' => 'Content',
                'rule_type' => 'exist',
                'config' => ['selector' => 'h1'],
                'severity' => 'error',
                'issue_message' => 'Tag <h1> tidak ditemukan.',
                'reason_template' => 'H1 bertindak sebagai judul utama konten dan penting bagi pemahaman topik oleh mesin pencari.',
                'recommendation' => 'Gunakan tepat satu tag <h1> yang mendeskripsikan topik utama halaman.',
            ],
            [
                'code' => 'H1_COUNT',
                'name' => 'Only One H1 Tag',
                'category' => 'Content',
                'rule_type' => 'count',
                'config' => [
                    'selector' => 'h1',
                    'operator' => '=',
                    'expected' => 1,
                ],
                'severity' => 'warning',
                'issue_message' => 'Ditemukan lebih dari satu tag <h1>.',
                'reason_template' => 'Meskipun HTML5 mengizinkan banyak H1, praktik SEO terbaik menyarankan hanya 1 per halaman.',
                'recommendation' => 'Ganti tag <h1> berlebih dengan <h2> atau tag heading yang lebih kecil.',
            ],
            [
                'code' => 'IMG_ALT_EXISTS',
                'name' => 'Images Have Alt Attributes',
                'category' => 'Media',
                'rule_type' => 'attribute',
                'config' => [
                    'selector' => 'img',
                    'attribute' => 'alt',
                    'condition' => 'exists',
                ],
                'severity' => 'error',
                'issue_message' => 'Ada gambar (<img>) yang tidak memiliki atribut alt.',
                'reason_template' => 'Atribut alt diwajibkan untuk aksesibilitas (screen reader) dan image SEO.',
                'recommendation' => 'Tambahkan atribut alt pada setiap tag <img>. Jika hanya dekoratif, gunakan alt="".',
            ],
            [
                'code' => 'IMG_ALT_NOT_EMPTY',
                'name' => 'Images Have Non-Empty Alt Attributes',
                'category' => 'Media',
                'rule_type' => 'attribute',
                'config' => [
                    'selector' => 'img',
                    'attribute' => 'alt',
                    'condition' => 'not_empty',
                ],
                'severity' => 'warning',
                'issue_message' => 'Beberapa gambar memiliki atribut alt kosong.',
                'reason_template' => 'Alt kosong (alt="") sah untuk gambar dekoratif, namun gambar informatif harus memiliki teks deskriptif.',
                'recommendation' => 'Pastikan alt kosong ini memang untuk gambar dekoratif. Jika informatif, isilah dengan teks.',
            ],
            [
                'code' => 'LINK_EMPTY_HREF',
                'name' => 'Links Have Non-Empty Href',
                'category' => 'Links',
                'rule_type' => 'attribute',
                'config' => [
                    'selector' => 'a',
                    'attribute' => 'href',
                    'condition' => 'not_empty',
                ],
                'severity' => 'warning',
                'issue_message' => 'Beberapa tautan memiliki atribut href kosong (href="").',
                'reason_template' => 'Tautan kosong tidak dapat diikuti oleh mesin pencari atau pengguna.',
                'recommendation' => 'Berikan URL valid atau gunakan tombol (<button>) jika elemen ini ditujukan untuk aksi JavaScript.',
            ],
            [
                'code' => 'LINK_HASH_ONLY',
                'name' => 'Avoid Hash Only Links',
                'category' => 'Links',
                'rule_type' => 'count',
                'config' => [
                    'selector' => 'a[href="#"]',
                    'operator' => '=',
                    'expected' => 0,
                ],
                'severity' => 'warning',
                'issue_message' => 'Ditemukan tautan dengan href="#".',
                'reason_template' => 'Penggunaan href="#" buruk bagi aksesibilitas dan SEO. Sebaiknya gunakan elemen <button>.',
                'recommendation' => 'Ganti tag <a> dengan <button> untuk interaksi UI yang tidak mengubah URL.',
            ],
            [
                'code' => 'LINK_HREF_EXISTS',
                'name' => 'Links Have Href Attribute',
                'category' => 'Links',
                'rule_type' => 'link',
                'config' => [
                    'condition' => 'href_exists',
                    'selector' => 'a',
                ],
                'severity' => 'warning',
                'issue_message' => 'Ditemukan tag <a> tanpa atribut href.',
                'reason_template' => 'Tag <a> tanpa href bukan merupakan hyperlink yang valid.',
                'recommendation' => 'Pastikan setiap tag <a> memiliki atribut href.',
            ],
            [
                'code' => 'LINK_TARGET_BLANK_REL',
                'name' => 'Target Blank Links Use Noopener',
                'category' => 'Links',
                'rule_type' => 'link',
                'config' => [
                    'condition' => 'target_blank_rel',
                    'expected' => 'noopener',
                ],
                'severity' => 'warning',
                'issue_message' => 'Link target="_blank" tidak menyertakan rel="noopener".',
                'reason_template' => 'Membuka jendela baru tanpa rel="noopener" rentan terhadap eksploitasi tabnabbing.',
                'recommendation' => 'Tambahkan rel="noopener" atau rel="noreferrer" pada link target="_blank".',
            ],
            [
                'code' => 'PAGE_HTTPS',
                'name' => 'Page Uses HTTPS Protocol',
                'category' => 'Technical',
                'rule_type' => 'url_match',
                'config' => [
                    'target' => 'page_url',
                    'condition' => 'protocol',
                    'operator' => 'equals',
                    'expected' => 'https',
                ],
                'severity' => 'warning',
                'issue_message' => 'Halaman tidak disajikan melalui protokol aman HTTPS.',
                'reason_template' => 'HTTPS adalah standar keamanan web modern dan sinyal peringkat pencarian.',
                'recommendation' => 'Migrasikan URL dan server untuk selalu menggunakan HTTPS.',
            ],
            [
                'code' => 'CANONICAL_SELF_REFERENCE',
                'name' => 'Canonical Matches Current Page URL',
                'category' => 'Metadata',
                'rule_type' => 'url_match',
                'config' => [
                    'target' => 'canonical_match',
                    'condition' => 'canonical_match',
                ],
                'severity' => 'warning',
                'issue_message' => 'Canonical URL tidak cocok dengan URL halaman saat ini.',
                'reason_template' => 'Jika halaman ini adalah versi utama, canonical sebaiknya menunjuk ke URL ini sendiri (self-referencing).',
                'recommendation' => 'Periksa apakah canonical sengaja menunjuk ke halaman lain atau terjadi kesalahan URL.',
            ],
            [
                'code' => 'HREFLANG_EXISTS',
                'name' => 'Hreflang Exists',
                'category' => 'International',
                'rule_type' => 'exist',
                'config' => ['selector' => 'link[rel="alternate"][hreflang]'],
                'severity' => 'warning',
                'issue_message' => 'Tag hreflang tidak ditemukan.',
                'reason_template' => 'Diperlukan hanya jika website Anda memiliki variasi bahasa atau wilayah lain.',
                'recommendation' => 'Jika website multi-bahasa, tambahkan rel="alternate" hreflang.',
                'is_active' => false,
            ],
            [
                'code' => 'HREFLANG_HAS_HREF',
                'name' => 'Hreflang Has Href',
                'category' => 'International',
                'rule_type' => 'attribute',
                'config' => [
                    'selector' => 'link[rel="alternate"][hreflang]',
                    'attribute' => 'href',
                    'condition' => 'not_empty',
                ],
                'severity' => 'error',
                'issue_message' => 'Tag hreflang kehilangan atribut href.',
                'reason_template' => 'Setiap deklarasi hreflang wajib menunjuk pada sebuah URL.',
                'recommendation' => 'Tambahkan URL ke dalam atribut href.',
            ],
            [
                'code' => 'AMP_TITLE_MATCH',
                'name' => 'Title matches AMP',
                'category' => 'AMP',
                'rule_type' => 'compare_amp',
                'config' => ['selector' => 'title'],
                'severity' => 'warning',
                'issue_message' => 'Title LP dan AMP tidak identik.',
                'reason_template' => 'Konsistensi metadata sangat disarankan antara versi canonical dan AMP.',
                'recommendation' => 'Samakan isi <title> pada halaman utama dan AMP.',
            ],
            [
                'code' => 'AMP_DESC_MATCH',
                'name' => 'Meta Desc matches AMP',
                'category' => 'AMP',
                'rule_type' => 'compare_amp',
                'config' => [
                    'selector' => 'meta[name="description"]',
                    'attribute' => 'content',
                ],
                'severity' => 'warning',
                'issue_message' => 'Meta description LP dan AMP tidak identik.',
                'reason_template' => 'Konsistensi metadata sangat disarankan.',
                'recommendation' => 'Samakan isi atribut content pada halaman utama dan AMP.',
            ],
            // ==================
            // Validation & GTAG
            // ==================
            [
                'code' => 'GTAG_VALID',
                'name' => 'GTAG matches Brand ID',
                'category' => 'Technical',
                'rule_type' => 'gtag',
                'config' => [],
                'severity' => 'error',
                'issue_message' => 'gtag tidak sesuai',
                'reason_template' => 'GTAG ID dari brand Anda tidak ditemukan di dalam HTML.',
                'recommendation' => 'Pastikan ID GTAG yang terdaftar di menu Brands ada di dalam HTML halaman ini.',
            ],
            [
                'code' => 'ALTERNATE_AMP_VALID',
                'name' => 'Valid AMP Alternate Link',
                'category' => 'AMP',
                'rule_type' => 'alternate',
                'config' => [
                    'rel_type' => 'amphtml',
                    'target_type' => 'amp'
                ],
                'severity' => 'error',
                'issue_message' => 'link rel amphtml tidak ditemukan atau tidak sesuai',
                'reason_template' => 'Halaman utama harus menunjuk ke URL AMP yang benar menggunakan <link rel="amphtml">.',
                'recommendation' => 'Tambahkan atau perbaiki tag <link rel="amphtml" href="..."> agar mengarah persis ke URL AMP.',
            ],
        ];
    }
    
    public static function populateFor($user)
    {
        $rules = self::getRules();
        $i = 0;
        foreach ($rules as $rule) {
            $i++;
            $user->rules()->create(array_merge($rule, ['sort_order' => $i]));
        }
    }
}
